"""
简单示例：加载 generate_rough_terrain.py 生成的 Mujoco 场景。

默认加载 auto_scene_terrain.xml，你也可以通过命令行参数指定其它文件名。

运行示例（在项目根目录）：

    cd /home/ares/Desktop/LeggedLab
    python legged_lab/assets/ares/a1/load_auto_scene_terrain.py

需要你已经安装 Mujoco 官方 Python 包：
    pip install mujoco
"""

import argparse
import os

import mujoco as mj

try:
    # mujoco>=3.0 提供交互式可视化
    import mujoco.viewer as viewer  # type: ignore
except Exception:  # pragma: no cover - viewer 可能不可用（比如无显示环境）
    viewer = None


def load_model(xml_filename: str = "auto_scene_terrain.xml") -> mj.MjModel:
    """
    从当前脚本所在目录加载 XML 并返回 Mujoco MjModel。
    """
    this_dir = os.path.dirname(os.path.abspath(__file__))
    xml_path = os.path.join(this_dir, xml_filename)

    if not os.path.exists(xml_path):
        raise FileNotFoundError(f"XML file not found: {xml_path}")

    print(f"Loading Mujoco scene from: {xml_path}")
    model = mj.MjModel.from_xml_path(xml_path)
    return model


def run_headless_step(model: mj.MjModel, steps: int = 1000) -> None:
    """
    无可视化地跑一小段仿真，主要是测试能否正常加载/step。
    """
    data = mj.MjData(model)
    for i in range(steps):
        mj.mj_step(model, data)
    print(f"Headless simulation finished {steps} steps.")


def run_with_viewer(model: mj.MjModel) -> None:
    """
    如果环境支持 viewer，则打开一个交互式窗口。
    """
    if viewer is None:
        print("mujoco.viewer not available, fallback to headless simulation.")
        run_headless_step(model)
        return

    data = mj.MjData(model)
    print("Starting interactive viewer. Close the window to exit.")
    with viewer.launch_passive(model, data) as v:
        while v.is_running():
            mj.mj_step(model, data)
            v.sync()


def main():
    parser = argparse.ArgumentParser(
        description="Load and run Mujoco scene generated by generate_rough_terrain.py"
    )
    parser.add_argument(
        "--xml",
        type=str,
        default="auto_scene_terrain.xml",
        help="XML filename to load (relative to this script directory).",
    )
    parser.add_argument(
        "--headless",
        action="store_true",
        help="Run without viewer (only stepping simulation).",
    )
    args = parser.parse_args()

    model = load_model(args.xml)

    if args.headless:
        run_headless_step(model)
    else:
        run_with_viewer(model)


if __name__ == "__main__":
    main()

